version: 0.0
os: linux
files:
  - source: layout/var/www
    destination: /var/www
  - source: layout/etc/awslogs/awslogs.conf
    destination: /etc/awslogs
  - source: layout/etc/nginx/nginx.conf
    destination: /etc/nginx
  - source: layout/etc/nginx/conf.d
    destination: /etc/nginx/conf.d
  - source: layout/etc/php.ini
    destination: /etc
  - source: layout/etc/php-fpm.conf
    destination: /etc
  - source: layout/etc/php-fpm.d
    destination: /etc/php-fpm.d
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/
    owner: nginx
    group: nginx
hooks:
  BeforeInstall:
    - location: scripts/stop-service.sh
  AfterInstall:
    - location: scripts/start-service.sh
      timeout: 180